package com.telkomsel.itvas.garudasmscrew;

public enum PushType {
	PUBLISH, REVISE, FAMILY_REASON, FREE_MESSAGE, ETD, PULL_ANSWER_PUB, PULL_ANSWER_SCH, PULL_ANSWER_CKI, PULL_ANSWER_CPP, PULL_ANSWER_FRE, PULL_ANSWER_FAT, PULL_ANSWER_MISC
}
